---
development:
  encoding: unicode
  adapter: postgresql
  database: release_tracker_dev
  host: localhost

production:
  encoding: unicode
  adapter: postgresql
  database: release_tracker_production
  host: localhost
  
test:
  encoding: unicode
  adapter: postgresql
  database: release_tracker_test
  host: localhost
